name: nyc-mta-api
region: nyc

services:
  - name: api
    # Build from source
    github:
      repo: mud2monarch/nyc-mta-pi
      branch: main
      deploy_on_push: true

    # Build configuration (DO auto-installs uv and runs uv sync)
    run_command: python -m uvicorn src.api:app --host 0.0.0.0 --port 8080

    # Instance size (basic = $5/month)
    instance_count: 1
    instance_size_slug: basic-xxs

    # HTTP configuration
    http_port: 8080

    # Environment variables (if needed)
    # envs:
    #   - key: ENV_VAR_NAME
    #     value: "some_value"

    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 30

    # Routes
    routes:
      - path: /
