name: nyc-mta-api
region: nyc

services:
  - name: api
    # Build from Dockerfile
    github:
      repo: mud2monarch/nyc-mta-pi
      branch: main
      deploy_on_push: true

    dockerfile_path: Dockerfile

    # Instance size (basic = $5/month)
    instance_count: 1
    instance_size_slug: basic-xxs

    # HTTP configuration
    http_port: 8080

    # Environment variables (if needed)
    # envs:
    #   - key: ENV_VAR_NAME
    #     value: "some_value"

    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 30

    # Routes
    routes:
      - path: /
